/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.text.SimpleDateFormat;
import modelo.Intangible;
import modelo.IntangibleDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author esqui
 */
public class FrmReportes extends javax.swing.JFrame {

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
        mostrarTotales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        lblTotalIntangiblesValor = new javax.swing.JLabel();
        lblSumaCostosValor = new javax.swing.JLabel();
        lblPromVidaValor = new javax.swing.JLabel();
        lblTotalRemanenteValor = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblTotalIntangibles = new javax.swing.JLabel();
        lblSumaCostos = new javax.swing.JLabel();
        lblPromVida = new javax.swing.JLabel();
        lblTotalRemanente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblVida = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblAnual = new javax.swing.JLabel();
        lblMensual = new javax.swing.JLabel();
        lblLibros = new javax.swing.JLabel();
        lblRemanente = new javax.swing.JLabel();
        lblCuotas = new javax.swing.JLabel();
        lblCuotasAm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reporte de Intangibles");
        setBackground(new java.awt.Color(23, 45, 64));

        jPanel2.setBackground(new java.awt.Color(23, 45, 64));

        lblTotalIntangiblesValor.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblTotalIntangiblesValor.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalIntangiblesValor.setText("0000");

        lblSumaCostosValor.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblSumaCostosValor.setForeground(new java.awt.Color(255, 255, 255));
        lblSumaCostosValor.setText("0000");

        lblPromVidaValor.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblPromVidaValor.setForeground(new java.awt.Color(255, 255, 255));
        lblPromVidaValor.setText("0000");

        lblTotalRemanenteValor.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblTotalRemanenteValor.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalRemanenteValor.setText("0000");

        btnActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizar.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(102, 102, 102));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(102, 102, 102));
        btnVolver.setText("Volver al menú principal");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblTotalIntangibles.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblTotalIntangibles.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalIntangibles.setText("Total de intangibles:");

        lblSumaCostos.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblSumaCostos.setForeground(new java.awt.Color(255, 255, 255));
        lblSumaCostos.setText("Suma total de costos:");

        lblPromVida.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblPromVida.setForeground(new java.awt.Color(255, 255, 255));
        lblPromVida.setText("Promedio de vida útil:");

        lblTotalRemanente.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblTotalRemanente.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalRemanente.setText("Total remanente:");

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Datos Promedios Obtenidos de la Base de Datos:");

        txtIdBuscar.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        txtIdBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtIdBuscar.setPreferredSize(new java.awt.Dimension(50, 30));
        txtIdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(102, 102, 102));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setPreferredSize(new java.awt.Dimension(60, 25));

        lblTipo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setPreferredSize(new java.awt.Dimension(60, 25));

        lblFecha.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setPreferredSize(new java.awt.Dimension(60, 25));

        lblVida.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblVida.setForeground(new java.awt.Color(255, 255, 255));
        lblVida.setPreferredSize(new java.awt.Dimension(60, 25));

        lblCosto.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblCosto.setForeground(new java.awt.Color(255, 255, 255));
        lblCosto.setPreferredSize(new java.awt.Dimension(60, 25));

        lblAnual.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblAnual.setForeground(new java.awt.Color(255, 255, 255));
        lblAnual.setPreferredSize(new java.awt.Dimension(60, 25));

        lblMensual.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblMensual.setForeground(new java.awt.Color(255, 255, 255));
        lblMensual.setPreferredSize(new java.awt.Dimension(60, 25));

        lblLibros.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblLibros.setForeground(new java.awt.Color(255, 255, 255));
        lblLibros.setPreferredSize(new java.awt.Dimension(60, 25));

        lblRemanente.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblRemanente.setForeground(new java.awt.Color(255, 255, 255));
        lblRemanente.setPreferredSize(new java.awt.Dimension(60, 25));

        lblCuotas.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblCuotas.setForeground(new java.awt.Color(255, 255, 255));
        lblCuotas.setPreferredSize(new java.awt.Dimension(60, 25));

        lblCuotasAm.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblCuotasAm.setForeground(new java.awt.Color(255, 255, 255));
        lblCuotasAm.setPreferredSize(new java.awt.Dimension(60, 25));

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Busca de Intagibles por ID:");

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos Obtenidos de la Busqueda:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCuotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRemanente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTotalIntangibles)
                                            .addComponent(lblSumaCostos)
                                            .addComponent(lblPromVida)
                                            .addComponent(lblTotalRemanente))
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTotalRemanenteValor)
                                            .addComponent(lblPromVidaValor)
                                            .addComponent(lblSumaCostosValor)
                                            .addComponent(lblTotalIntangiblesValor)))
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblVida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblAnual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblMensual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCuotasAm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalIntangibles)
                    .addComponent(lblTotalIntangiblesValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSumaCostos)
                    .addComponent(lblSumaCostosValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPromVida)
                    .addComponent(lblPromVidaValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalRemanente)
                    .addComponent(lblTotalRemanenteValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemanente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCuotasAm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnVolver))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        mostrarTotales(); // recalcula y muestra los totales generales
        txtIdBuscar.setText(""); // opcional: limpia el campo de búsqueda
        // Limpiar los labels de detalle
        lblNombre.setText("Nombre del Tutor: ");
        lblTipo.setText("Tipo Licencia: ");
        lblFecha.setText("Fecha Adquisición: ");
        lblVida.setText("Vida útil: ");
        lblCosto.setText("Costo: ");
        lblAnual.setText("Amortización anual: ");
        lblMensual.setText("Amortización mensual: ");
        lblLibros.setText("Valor en libros: ");
        lblRemanente.setText("Remanente: ");
        lblCuotas.setText("Cuotas totales: ");
        lblCuotasAm.setText("Cuotas amortizadas: ");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        FrmMenu frm = new FrmMenu();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtIdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBuscarActionPerformed
        txtIdBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
            if (!Character.isDigit(c)) {
                evt.consume(); // ignora cualquier cosa que no sea número
                }
            }
        });
    }//GEN-LAST:event_txtIdBuscarActionPerformed
 
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarIntangibleporID();
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReportes().setVisible(true);
            }
        });
    }
    
    private void mostrarTotales(){
        IntangibleDAO dao = new IntangibleDAO();
        ArrayList<Intangible> lista = dao.listarIntangibles();
        
        int totalIntangibles = lista.size();
        double sumaCostos = 0;
        double sumaRemanentes = 0;
        int sumaVidaUtil = 0;
        
        for(Intangible i : lista){
            sumaCostos += i.getCosto();
            sumaRemanentes += i.getRemanente();
            sumaVidaUtil += i.getVidaUtil();
        }
        
        double promedioVida = (totalIntangibles > 0) ? 
                (double) sumaVidaUtil / totalIntangibles : 0;
        
        //Mostrar resultados en las etiquetas
        lblTotalIntangiblesValor.setText(String.valueOf(totalIntangibles));
        lblSumaCostosValor.setText(String.format("%.2f", sumaCostos));
        lblPromVidaValor.setText(String.format("%.2f", promedioVida));
        lblTotalRemanenteValor.setText(String.format("%.2f", sumaRemanentes));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private javax.swing.JLabel lblAnual;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblCuotas;
    private javax.swing.JLabel lblCuotasAm;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLibros;
    private javax.swing.JLabel lblMensual;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPromVida;
    private javax.swing.JLabel lblPromVidaValor;
    private javax.swing.JLabel lblRemanente;
    private javax.swing.JLabel lblSumaCostos;
    private javax.swing.JLabel lblSumaCostosValor;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTotalIntangibles;
    private javax.swing.JLabel lblTotalIntangiblesValor;
    private javax.swing.JLabel lblTotalRemanente;
    private javax.swing.JLabel lblTotalRemanenteValor;
    private javax.swing.JLabel lblVida;
    private javax.swing.JTextField txtIdBuscar;
    // End of variables declaration//GEN-END:variables

    private void buscarIntangibleporID() {
        try {
            int id = Integer.parseInt(txtIdBuscar.getText());

            // Llamar al DAO para buscar el intangible por ID
            IntangibleDAO dao = new IntangibleDAO();
            ArrayList<Intangible> lista = dao.listarIntangibles();
            Intangible encontrado = null;

            for (Intangible i : lista) {
                if (i.getId() == id) {
                    encontrado = i;
                    break;
                }
            }
            if (encontrado != null) {
                //Formatear la fecha correcta
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                String fechaFormateada = encontrado.getFechaAdquisicion() 
                        != null ? sdf.format(encontrado.getFechaAdquisicion()) 
                        : "No disponible";
                // Mostrar los datos
                lblNombre.setText("Nombre del Tutor: " + encontrado.getNombre());
                lblTipo.setText("Tipo Licencia: " + encontrado.getTipoLicencia());
                lblFecha.setText("Fecha Adquisición: " + fechaFormateada);
                lblVida.setText("Vida útil: " + encontrado.getVidaUtil() + " Años" );
                lblCosto.setText("Costo: $" + encontrado.getCosto());
                lblAnual.setText("Amortización anual: $" + encontrado.getAmortizacionAnual());
                lblMensual.setText("Amortización mensual: $" + encontrado.getAmortizacionMensual());
                lblLibros.setText("Valor en libros: $" + encontrado.getValorLibros());
                lblRemanente.setText("Remanente: $" + encontrado.getRemanente());
                lblCuotas.setText("Cuotas totales: " + encontrado.getCuotasTotal());
                lblCuotasAm.setText("Cuotas amortizadas: " + encontrado.getCuotasAmortizadas());    
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ningún intangible con ID: " + id);
            }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingresa un número válido");
        }
    }
}
